package com.soulsalutte.soulsalutte.enums;

public enum EstadoConversa {
    LIVRE,
    AGUARDANDO_NOME,
    AGUARDANDO_EMAIL,
    AGUARDANDO_DATA_NASCIMENTO,
    AGUARDANDO_TELEFONE,
    ESCOLHENDO_SERVICO,
    ESCOLHENDO_DATA,
    ESCOLHENDO_HORARIO,
    CONFIRMANDO_AGENDAMENTO,
    AGENDAMENTO_CONCLUIDO,
    CANCELANDO_AGENDAMENTO,
    ALTERANDO_AGENDAMENTO
}

